apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld #  ← label совпадает с Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: nginx:alpine # для проверки. потом подставишь свой образ
          ports:
            - containerPort: 80 # nginx слушает 80
