name: Build & Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Тег образа (например v1.2.3)"
        required: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/helloworld

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      # ---------- 1. Checkout код (main) и собираем образ ----------
      - name: Checkout main (source code)
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR via PAT # ← заменили
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Build & push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE_NAME:${{ github.event.inputs.version }} \
            -t $IMAGE_NAME:latest \
            --push .

      # ---------- 2. Переключаемся на ветку deploy ----------
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy
          path: deploy-repo # кладём во вторую папку

      - name: Install yq
        run: |
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Patch image tag in deployment.yaml
        working-directory: deploy-repo
        run: |
          yq -i '.spec.template.spec.containers[0].image = "'$IMAGE_NAME':${{ github.event.inputs.version }}"' manifests/deployment.yaml
          echo "🔍 Новый образ:"
          yq '.spec.template.spec.containers[0].image' manifests/deployment.yaml

      - name: Commit & push to deploy
        working-directory: deploy-repo
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git add manifests/deployment.yaml
          git commit -m "deploy: $IMAGE_NAME:${{ github.event.inputs.version }}"
          git push origin HEAD:deploy
